### PR TITLE
chore: Increase Django REST Framework required maximum version to 3.13.x

### PR DESCRIPTION
**Pull request by fpinto-cdd**
Increase limit to 3.14 as the latest release is at version 3.13.1.

Changelog:

- 3.13.1 (2021-12-15):
  https://www.django-rest-framework.org/community/release-notes/#3131
- 3.13.0 (2021-12-13):
  https://www.django-rest-framework.org/community/release-notes/#3130

Code diff: https://github.com/encode/django-rest-framework/compare/3.12.4...3.13.1

Fixes: https://github.com/fyntex/lib-cl-sii-python/issues/270

### CODE REVIEW

**Review by ycouce-cdd — APPROVED** [review]

**Review by jtrobles-cdd — COMMENTED** [review]
Why does the _code diff_ start at version `3.11.2`?

**Comment by jtrobles-cdd** [comment]
> > Why does the _code diff_ start at version `3.11.2`?
> 
> I was not sure about the starting version since it only specify a range and 3.11.2 is the actual version in the project that depends on this lib.
> 
> Should I start from 3.13.0?

I'm also not sure about which version range to use. I think that in the future we'll keep using a version range in `setup.py`, but we'll switch to using a specific version in `requirements/extras.txt`.

However, for the current pull request, I think we could follow the following steps to define a version range:

- Create an _empty_ Python 3.8 virtual environment.
- Execute `pip install 'djangorestframework>=3.10.3,<3.13'`. This installs version `3.12.4`.
- Execute `pip install --upgrade 'djangorestframework>=3.10.3,<3.14'`. This installs version `3.13.1`.

Conclusion: For the purposes of listing changelogs and the code diff, let's assume that we're updating from version `3.12.4` to `3.13.1`.

**Review by jtrobles-cdd — CHANGES_REQUESTED** [review]
Following the version range procedure described in https://github.com/fyntex/lib-cl-sii-python/pull/292#issuecomment-1033029564, let's change the *code diff* to https://github.com/encode/django-rest-framework/compare/3.12.4...3.13.1 and for the changelogs start at `3.13.0`.

**Comment by fpinto-cdd** [comment]
For some reason I can't update this branch using rebase

**Review by jtrobles-cdd — APPROVED** [review]

**Pull request merged**
